# generated by datamodel-codegen:
#   filename:  stock_schema.json
#   timestamp: 2026-01-28T11:41:46+00:00

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel


class Stock(BaseModel):
    symbol: str
    price: float
    change: float
    percent_change: float
    last_updated: AwareDatetime
